Repository DewyKB/dewy, pull requests merged in 2024-03, with the labels that each got.

#102 fix: CI lint and test issues
  .github/workflows/ci.yml
  dewy-client/dewy_client/__init__.py
  dewy-client/dewy_client/api/__init__.py
  dewy-client/dewy_client/api/kb/add_document.py
  dewy-client/dewy_client/errors.py
  dewy-client/dewy_client/models/__init__.py
  dewy-client/dewy_client/types.py
  dewy-client/pyproject.toml
  dewy/common/collection_embeddings.py
  openapi.yaml
  poetry.lock
  pyproject.toml
  tests/test_e2e.py
Labels: bug

#101 feat: Separate commands / options for Dewy
  .github/workflows/ci.yml
  Dockerfile
  demos/python-langchain-cli/pyproject.toml
  dewy/__main__.py
  dewy/async_command.py
  dewy/common/collection_embeddings.py
  dewy/common/embeddings.py
  dewy/config.py
  dewy/constants.py
  dewy/document/router.py
  dewy/main.py
  dewy/migration.py
  dewy/serve.py
  docker-compose.yml
  openapi.yaml
  poetry.lock
  pyproject.toml
  scripts/extract_openapi.py
  tests/conftest.py
Labels: enhancement

#103 feat: Support markdown, html, and docx
  dewy/common/collection_embeddings.py
  dewy/common/extract.py
  dewy/document/models.py
  dewy/document/router.py
  openapi.yaml
  poetry.lock
  pyproject.toml
  test_data/nearly_empty.docx
  test_data/nearly_empty.html
  test_data/nearly_empty.md
  tests/conftest.py
  tests/test_extract.py
Labels: enhancement

#105 refactor: Simplify filetype handling
  dewy/common/extract.py
  poetry.lock
  pyproject.toml
Labels: refactor

#104 feat: Add the ability to load documents from local files in UI
  dewy-client/dewy_client/api/kb/list_chunks.py
  dewy/chunk/router.py
  dewy/common/collection_embeddings.py
  dewy/frontend/dist/assets/index-a8d960f9.js
  dewy/frontend/dist/assets/index-aff91d9d.js
  dewy/frontend/dist/index.html
  dewy/frontend/src/App.tsx
  dewy/frontend/src/Chunk.tsx
  dewy/frontend/src/Document.tsx
  dewy/frontend/src/Search.tsx
  dewy/frontend/src/dataProvider.ts
  openapi.yaml
Labels: enhancement

#108 chore: Update labels.yml
  .github/labels.yml
Labels: chore

#107 feat!: Use taskiq for durable ingestion
  README.md
  dewy-client/dewy_client/api/kb/add_collection.py
  dewy-client/dewy_client/api/kb/delete_document.py
  dewy-client/dewy_client/api/kb/get_document_status.py
  dewy-client/dewy_client/api/kb/retrieve_chunks.py
  dewy-client/dewy_client/models/__init__.py
  dewy-client/dewy_client/models/collection.py
  dewy-client/dewy_client/models/collection_create.py
  dewy-client/dewy_client/models/document_status.py
  dewy-client/dewy_client/models/image_result.py
  dewy-client/dewy_client/models/retrieve_response.py
  dewy-client/dewy_client/models/retrieved_chunks.py
  dewy-client/dewy_client/models/text_chunk.py
  dewy-client/dewy_client/models/text_result.py
  dewy/backend/__init__.py
  dewy/backend/_dependencies.py
  dewy/backend/chunks_api.py
  dewy/backend/collections_api.py
  dewy/backend/documents_api.py
  dewy/chunk/models.py
  dewy/chunk/router.py
  dewy/collection/__init__.py
  dewy/collection/models.py
  dewy/collection/router.py
  dewy/common/collection_embeddings.py
  dewy/common/db.py
  dewy/common/extract.py
  dewy/config.py
  dewy/document/__init__.py
  dewy/document/models.py
  dewy/document/router.py
  dewy/domain/__init__.py
  dewy/domain/_errors.py
  dewy/domain/chunks.py
  dewy/domain/collection.py
  dewy/domain/database.py
  dewy/domain/documents.py
  dewy/domain/embedding_models.py
  dewy/domain/embeddings.py
  dewy/domain/ingest.py
  dewy/frontend/src/Search.tsx
  dewy/migration.py
  dewy/routes.py
  dewy/serve.py
  dewy/tasks/__init__.py
  dewy/tasks/_dependencies.py
  dewy/tasks/_ingest.py
  dewy/tasks/dewy_tasks.py
  openapi.yaml
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_chunks.py
  tests/test_collection.py
  tests/test_documents.py
  tests/test_e2e.py
Labels: enhancement, breaking

#111 feat: Load .env files
  dewy/main.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#113 fix: handle mimetypes with encodings
  dewy/common/extract.py
  tests/test_extract.py
Labels: bug
