Repository DewyKB/dewy, pull requests merged in 2024-02, with the labels that each got.

#59 ci: Initial release workflows
  .github/workflows/README.md
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  README.md
Labels: ci

#60 chore: Prepare v0.1.1 release
  README.md
  dewy-client/pyproject.toml
  dewy/config.py
  openapi.yaml
  pyproject.toml
Labels: chore

#61 ci: Fixes to the release script
  .github/workflows/release.yml
Labels: ci

#62 feat: Allow listing collection by name
  dewy-client/dewy_client/api/default/list_collections.py
  dewy-client/poetry.lock
  dewy-client/pyproject.toml
  dewy/collection/router.py
  dewy/config.py
  openapi.yaml
  pyproject.toml
  tests/test_collection.py
Labels: enhancement

#63 ci: remove prerelease when finalizing
  .github/workflows/release.yml
Labels: ci

#58 docs: Barebones docs based on README
  docs/docs/Getting Started/admin_ui.md
  docs/docs/Getting Started/clients.md
  docs/docs/Getting Started/configuration.md
  docs/docs/Getting Started/installation.md
  docs/docs/User Manual/concepts.md
  docs/docs/intro.md
  docs/docs/intro.mdx
  docs/docusaurus.config.ts
  docs/sidebars.ts
Labels: docs

#64 docs: Fix README.md for PyPi
  README.md
Labels: docs

#67 feat: Create notebook based demos
  .github/workflows/ci.yml
  Dockerfile
  demos/python-langchain-notebook/.gitignore
  demos/python-langchain-notebook/python-langchain.ipynb
  dewy/common/collection_embeddings.py
Labels: enhancement

#70 docs: Remove docs (moved to a separate repo)
  .github/workflows/site.yml
  docs/README.md
  docs/babel.config.js
  docs/blog/authors.yml
  docs/docs/Getting Started/admin_ui.md
  docs/docs/Getting Started/clients.md
  docs/docs/Getting Started/configuration.md
  docs/docs/Getting Started/installation.md
  docs/docs/User Manual/concepts.md
  docs/docs/intro.mdx
  docs/docusaurus.config.ts
  docs/package.json
  docs/sidebars.ts
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/static/.nojekyll
  docs/static/img/favicon.ico
  docs/static/img/logo.png
  docs/tsconfig.json
  docs/yarn.lock
Labels: docs

#71 build: Cut a new minor release
  dewy-client/pyproject.toml
  dewy/config.py
  openapi.yaml
  pyproject.toml
Labels: build

#69 feat: Update document with ingest errors
  dewy/document/router.py
  poetry.lock
  pyproject.toml
  tests/test_e2e.py
Labels: enhancement

#76 feat: Add `GET /documents/{id}/status`
  dewy-client/dewy_client/api/default/get_document_status.py
  dewy-client/dewy_client/models/__init__.py
  dewy-client/dewy_client/models/document.py
  dewy-client/dewy_client/models/document_status.py
  dewy/common/db_migration.py
  dewy/document/models.py
  dewy/document/router.py
  dewy/migrations/0001_schema.sql
  openapi.yaml
  pyproject.toml
  tests/test_e2e.py
Labels: enhancement

#78 refactor: Switch to a factory method for the app
  Dockerfile
  dewy/chunk/router.py
  dewy/common/collection_embeddings.py
  dewy/config.py
  dewy/document/router.py
  dewy/main.py
  pyproject.toml
  scripts/extract_openapi.py
  tests/conftest.py
Labels: refactor

#86 feat!: Tag methods `kb` to create `dewy.kb`
  README.md
  demos/python-langchain-notebook/python-langchain.ipynb
  dewy-client/README.md
  dewy-client/dewy_client/api/kb/__init__.py
  dewy-client/dewy_client/api/kb/add_collection.py
  dewy-client/dewy_client/api/kb/add_document.py
  dewy-client/dewy_client/api/kb/get_chunk.py
  dewy-client/dewy_client/api/kb/get_collection.py
  dewy-client/dewy_client/api/kb/get_document.py
  dewy-client/dewy_client/api/kb/get_document_status.py
  dewy-client/dewy_client/api/kb/list_chunks.py
  dewy-client/dewy_client/api/kb/list_collections.py
  dewy-client/dewy_client/api/kb/list_documents.py
  dewy-client/dewy_client/api/kb/retrieve_chunks.py
  dewy-client/dewy_client/api/kb/upload_document_content.py
  dewy/routes.py
  example_notebook.ipynb
  openapi.yaml
  tests/test_collection.py
  tests/test_e2e.py
Labels: enhancement, breaking

#89 feat!: Use collection names in the API
  dewy-client/dewy_client/api/kb/get_collection.py
  dewy-client/dewy_client/api/kb/list_chunks.py
  dewy-client/dewy_client/api/kb/list_collections.py
  dewy-client/dewy_client/api/kb/list_documents.py
  dewy-client/dewy_client/models/add_document_request.py
  dewy-client/dewy_client/models/collection.py
  dewy-client/dewy_client/models/document.py
  dewy-client/dewy_client/models/retrieve_request.py
  dewy/chunk/models.py
  dewy/chunk/router.py
  dewy/collection/models.py
  dewy/collection/router.py
  dewy/common/collection_embeddings.py
  dewy/document/models.py
  dewy/document/router.py
  dewy/frontend/src/Collection.tsx
  dewy/migrations/0001_schema.sql
  openapi.yaml
  tests/test_chunks.py
  tests/test_collection.py
  tests/test_documents.py
  tests/test_e2e.py
Labels: enhancement, breaking

#90 chore: Prepare for 0.2.0 release
  dewy-client/pyproject.toml
  dewy/config.py
  openapi.yaml
  pyproject.toml
Labels: chore

#91 docs: update langchain notebook
  demos/python-langchain-notebook/python-langchain.ipynb
Labels: docs

#92 feat: Reset the document's state when a file is uploaded.
  README.md
  dewy/document/router.py
  test_data/nearly_empty2.pdf
  tests/conftest.py
  tests/test_documents.py
Labels: enhancement

#95 ci: Bump version to 0.2.1
  dewy-client/pyproject.toml
  dewy/config.py
  openapi.yaml
  pyproject.toml
Labels: ci

#96 chore: Prepare the 0.3.0 release
  dewy-client/pyproject.toml
  dewy/config.py
  openapi.yaml
  poetry.lock
  pyproject.toml
Labels: chore

#97 refactor!: Enumerate supported embeddings
  dewy/collection/models.py
  dewy/collection/router.py
  dewy/common/collection_embeddings.py
  dewy/common/embeddings.py
  dewy/document/router.py
  dewy/migrations/0001_schema.sql
Labels: refactor, breaking

#98 refactor!: Switch to LangChain for abstractions
  dewy/common/collection_embeddings.py
  dewy/common/embeddings.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
  tests/test_e2e.py
Labels: refactor, breaking

#99 docs: Add langchain CLI demo
  .gitignore
  demos/python-langchain-cli/pyproject.toml
  demos/python-langchain-cli/python_langchain_cli/README.md
  demos/python-langchain-cli/python_langchain_cli/__init__.py
  demos/python-langchain-cli/python_langchain_cli/__main__.py
Labels: docs
